kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-sample-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-springboot-app
  template:
    metadata:
      labels:
        app: sample-springboot-app
    spec:
      containers:
        - name: my-sample-springboot
          image: docker.io/raketham/sampleproject:1.3
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-sample-springboot-svc
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: sample-springboot-app